ifdef OPT
CFLAGS+=-O$(OPT) -DNDEBUG
endif

ifeq ("$(LOG)","1")
CFLAGS+=-DDEBUG_LOGGING
endif

ifeq ("$(PROF)","1")
CFLAGS+=-pg
endif

# Note -- using scaled reciprocals instead of modulo
# is at least 2-3x faster for 32-bit integers on x64
ifeq ($(USE_RECIPS), 1)
CFLAGS+=-DUSE_PRIME_RECIPS=1
endif


